//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksWebService_client.BooksRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Books", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Books : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BooksRef.BooksWebServiceSoap")]
    public interface BooksWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetBooksResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBooks", ReplyAction="*")]
        BooksWebService_client.BooksRef.GetBooksResponse GetBooks(BooksWebService_client.BooksRef.GetBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebService_client.BooksRef.GetBooksResponse> GetBooksAsync(BooksWebService_client.BooksRef.GetBooksRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBook", ReplyAction="*")]
        BooksWebService_client.BooksRef.InsertBookResponse InsertBook(BooksWebService_client.BooksRef.InsertBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBook", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebService_client.BooksRef.InsertBookResponse> InsertBookAsync(BooksWebService_client.BooksRef.InsertBookRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBook", ReplyAction="*")]
        BooksWebService_client.BooksRef.DeleteBookResponse DeleteBook(BooksWebService_client.BooksRef.DeleteBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBook", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebService_client.BooksRef.DeleteBookResponse> DeleteBookAsync(BooksWebService_client.BooksRef.DeleteBookRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBook", ReplyAction="*")]
        BooksWebService_client.BooksRef.UpdateBookResponse UpdateBook(BooksWebService_client.BooksRef.UpdateBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBook", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebService_client.BooksRef.UpdateBookResponse> UpdateBookAsync(BooksWebService_client.BooksRef.UpdateBookRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBooks", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebService_client.BooksRef.GetBooksRequestBody Body;
        
        public GetBooksRequest() {
        }
        
        public GetBooksRequest(BooksWebService_client.BooksRef.GetBooksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBooksRequestBody {
        
        public GetBooksRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBooksResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebService_client.BooksRef.GetBooksResponseBody Body;
        
        public GetBooksResponse() {
        }
        
        public GetBooksResponse(BooksWebService_client.BooksRef.GetBooksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBooksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebService_client.BooksRef.Books[] GetBooksResult;
        
        public GetBooksResponseBody() {
        }
        
        public GetBooksResponseBody(BooksWebService_client.BooksRef.Books[] GetBooksResult) {
            this.GetBooksResult = GetBooksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBook", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebService_client.BooksRef.InsertBookRequestBody Body;
        
        public InsertBookRequest() {
        }
        
        public InsertBookRequest(BooksWebService_client.BooksRef.InsertBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string publisher;
        
        public InsertBookRequestBody() {
        }
        
        public InsertBookRequestBody(string id, string title, string author, string publisher) {
            this.id = id;
            this.title = title;
            this.author = author;
            this.publisher = publisher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebService_client.BooksRef.InsertBookResponseBody Body;
        
        public InsertBookResponse() {
        }
        
        public InsertBookResponse(BooksWebService_client.BooksRef.InsertBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebService_client.BooksRef.Books[] InsertBookResult;
        
        public InsertBookResponseBody() {
        }
        
        public InsertBookResponseBody(BooksWebService_client.BooksRef.Books[] InsertBookResult) {
            this.InsertBookResult = InsertBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBook", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebService_client.BooksRef.DeleteBookRequestBody Body;
        
        public DeleteBookRequest() {
        }
        
        public DeleteBookRequest(BooksWebService_client.BooksRef.DeleteBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DeleteBookRequestBody() {
        }
        
        public DeleteBookRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebService_client.BooksRef.DeleteBookResponseBody Body;
        
        public DeleteBookResponse() {
        }
        
        public DeleteBookResponse(BooksWebService_client.BooksRef.DeleteBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebService_client.BooksRef.Books[] DeleteBookResult;
        
        public DeleteBookResponseBody() {
        }
        
        public DeleteBookResponseBody(BooksWebService_client.BooksRef.Books[] DeleteBookResult) {
            this.DeleteBookResult = DeleteBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBook", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebService_client.BooksRef.UpdateBookRequestBody Body;
        
        public UpdateBookRequest() {
        }
        
        public UpdateBookRequest(BooksWebService_client.BooksRef.UpdateBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string publisher;
        
        public UpdateBookRequestBody() {
        }
        
        public UpdateBookRequestBody(string id, string title, string author, string publisher) {
            this.id = id;
            this.title = title;
            this.author = author;
            this.publisher = publisher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebService_client.BooksRef.UpdateBookResponseBody Body;
        
        public UpdateBookResponse() {
        }
        
        public UpdateBookResponse(BooksWebService_client.BooksRef.UpdateBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebService_client.BooksRef.Books[] UpdateBookResult;
        
        public UpdateBookResponseBody() {
        }
        
        public UpdateBookResponseBody(BooksWebService_client.BooksRef.Books[] UpdateBookResult) {
            this.UpdateBookResult = UpdateBookResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BooksWebServiceSoapChannel : BooksWebService_client.BooksRef.BooksWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BooksWebServiceSoapClient : System.ServiceModel.ClientBase<BooksWebService_client.BooksRef.BooksWebServiceSoap>, BooksWebService_client.BooksRef.BooksWebServiceSoap {
        
        public BooksWebServiceSoapClient() {
        }
        
        public BooksWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BooksWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebService_client.BooksRef.GetBooksResponse BooksWebService_client.BooksRef.BooksWebServiceSoap.GetBooks(BooksWebService_client.BooksRef.GetBooksRequest request) {
            return base.Channel.GetBooks(request);
        }
        
        public BooksWebService_client.BooksRef.Books[] GetBooks() {
            BooksWebService_client.BooksRef.GetBooksRequest inValue = new BooksWebService_client.BooksRef.GetBooksRequest();
            inValue.Body = new BooksWebService_client.BooksRef.GetBooksRequestBody();
            BooksWebService_client.BooksRef.GetBooksResponse retVal = ((BooksWebService_client.BooksRef.BooksWebServiceSoap)(this)).GetBooks(inValue);
            return retVal.Body.GetBooksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebService_client.BooksRef.GetBooksResponse> BooksWebService_client.BooksRef.BooksWebServiceSoap.GetBooksAsync(BooksWebService_client.BooksRef.GetBooksRequest request) {
            return base.Channel.GetBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebService_client.BooksRef.GetBooksResponse> GetBooksAsync() {
            BooksWebService_client.BooksRef.GetBooksRequest inValue = new BooksWebService_client.BooksRef.GetBooksRequest();
            inValue.Body = new BooksWebService_client.BooksRef.GetBooksRequestBody();
            return ((BooksWebService_client.BooksRef.BooksWebServiceSoap)(this)).GetBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebService_client.BooksRef.InsertBookResponse BooksWebService_client.BooksRef.BooksWebServiceSoap.InsertBook(BooksWebService_client.BooksRef.InsertBookRequest request) {
            return base.Channel.InsertBook(request);
        }
        
        public BooksWebService_client.BooksRef.Books[] InsertBook(string id, string title, string author, string publisher) {
            BooksWebService_client.BooksRef.InsertBookRequest inValue = new BooksWebService_client.BooksRef.InsertBookRequest();
            inValue.Body = new BooksWebService_client.BooksRef.InsertBookRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.publisher = publisher;
            BooksWebService_client.BooksRef.InsertBookResponse retVal = ((BooksWebService_client.BooksRef.BooksWebServiceSoap)(this)).InsertBook(inValue);
            return retVal.Body.InsertBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebService_client.BooksRef.InsertBookResponse> BooksWebService_client.BooksRef.BooksWebServiceSoap.InsertBookAsync(BooksWebService_client.BooksRef.InsertBookRequest request) {
            return base.Channel.InsertBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebService_client.BooksRef.InsertBookResponse> InsertBookAsync(string id, string title, string author, string publisher) {
            BooksWebService_client.BooksRef.InsertBookRequest inValue = new BooksWebService_client.BooksRef.InsertBookRequest();
            inValue.Body = new BooksWebService_client.BooksRef.InsertBookRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.publisher = publisher;
            return ((BooksWebService_client.BooksRef.BooksWebServiceSoap)(this)).InsertBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebService_client.BooksRef.DeleteBookResponse BooksWebService_client.BooksRef.BooksWebServiceSoap.DeleteBook(BooksWebService_client.BooksRef.DeleteBookRequest request) {
            return base.Channel.DeleteBook(request);
        }
        
        public BooksWebService_client.BooksRef.Books[] DeleteBook(string id) {
            BooksWebService_client.BooksRef.DeleteBookRequest inValue = new BooksWebService_client.BooksRef.DeleteBookRequest();
            inValue.Body = new BooksWebService_client.BooksRef.DeleteBookRequestBody();
            inValue.Body.id = id;
            BooksWebService_client.BooksRef.DeleteBookResponse retVal = ((BooksWebService_client.BooksRef.BooksWebServiceSoap)(this)).DeleteBook(inValue);
            return retVal.Body.DeleteBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebService_client.BooksRef.DeleteBookResponse> BooksWebService_client.BooksRef.BooksWebServiceSoap.DeleteBookAsync(BooksWebService_client.BooksRef.DeleteBookRequest request) {
            return base.Channel.DeleteBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebService_client.BooksRef.DeleteBookResponse> DeleteBookAsync(string id) {
            BooksWebService_client.BooksRef.DeleteBookRequest inValue = new BooksWebService_client.BooksRef.DeleteBookRequest();
            inValue.Body = new BooksWebService_client.BooksRef.DeleteBookRequestBody();
            inValue.Body.id = id;
            return ((BooksWebService_client.BooksRef.BooksWebServiceSoap)(this)).DeleteBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebService_client.BooksRef.UpdateBookResponse BooksWebService_client.BooksRef.BooksWebServiceSoap.UpdateBook(BooksWebService_client.BooksRef.UpdateBookRequest request) {
            return base.Channel.UpdateBook(request);
        }
        
        public BooksWebService_client.BooksRef.Books[] UpdateBook(string id, string title, string author, string publisher) {
            BooksWebService_client.BooksRef.UpdateBookRequest inValue = new BooksWebService_client.BooksRef.UpdateBookRequest();
            inValue.Body = new BooksWebService_client.BooksRef.UpdateBookRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.publisher = publisher;
            BooksWebService_client.BooksRef.UpdateBookResponse retVal = ((BooksWebService_client.BooksRef.BooksWebServiceSoap)(this)).UpdateBook(inValue);
            return retVal.Body.UpdateBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebService_client.BooksRef.UpdateBookResponse> BooksWebService_client.BooksRef.BooksWebServiceSoap.UpdateBookAsync(BooksWebService_client.BooksRef.UpdateBookRequest request) {
            return base.Channel.UpdateBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebService_client.BooksRef.UpdateBookResponse> UpdateBookAsync(string id, string title, string author, string publisher) {
            BooksWebService_client.BooksRef.UpdateBookRequest inValue = new BooksWebService_client.BooksRef.UpdateBookRequest();
            inValue.Body = new BooksWebService_client.BooksRef.UpdateBookRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.publisher = publisher;
            return ((BooksWebService_client.BooksRef.BooksWebServiceSoap)(this)).UpdateBookAsync(inValue);
        }
    }
}
